# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 2
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
        os: [ubuntu-16.04, ubuntu-18.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: sudo apt update
        if: ${{ matrix.os == 'ubuntu-16.04' || matrix.os == 'ubuntu-18.04' }}
      - run: sudo apt install -y libnetcdf-dev
        if: ${{ matrix.os == 'ubuntu-16.04' || matrix.os == 'ubuntu-18.04' }}
      - run: npm install
      - run: npm test
        env:
          CI: true
